# Generated by Django 5.2.6 on 2025-10-09 15:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_referralmilestoneprogress_referralmilestoneaward'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='referralmilestoneprogress',
            name='current_sum_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='referralmilestoneprogress',
            name='included_direct_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AlterUniqueTogether(
            name='referralpayout',
            unique_together={('referrer', 'referee', 'level')},
        ),
    ]
