services:
  # Backend API Service
  - type: web
    name: nexocart-backend
    env: python
    region: oregon
    plan: free
    buildCommand: |
      cd ref_backend &&
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput &&
      python manage.py migrate
    startCommand: |
      cd ref_backend &&
      gunicorn core.wsgi:application --config gunicorn.conf.py
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "0"
      - key: DATABASE_URL
        fromDatabase:
          name: nexocart-db
          property: connectionString
      - key: GUNICORN_WORKERS
        value: "2"
      - key: GUNICORN_THREADS
        value: "4"
      - key: ADMIN_USD_TO_PKR
        value: "280.0"
      - key: SIGNUP_FEE_PKR
        value: "1410"
      - key: USER_WALLET_SHARE
        value: "0.80"
      - key: WITHDRAW_TAX
        value: "0.20"
      - key: REFERRAL_TIERS
        value: "0.06,0.03,0.01"

  # Frontend Service
  - type: web
    name: nexocart-frontend
    env: static
    region: oregon
    plan: free
    buildCommand: |
      npm install &&
      npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Database
databases:
  - name: nexocart-db
    databaseName: nexocart
    user: nexocart_user
    region: oregon
    plan: free