# Generated by Django 5.0.7 on 2025-09-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_order_guest_email_order_guest_name_order_guest_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='orders/'),
        ),
    ]
