# Generated by Django 5.2.6 on 2025-10-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earnings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEarningsState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_processed_date', models.DateField()),
                ('last_processed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Earnings State',
                'verbose_name_plural': 'Daily Earnings State',
            },
        ),
    ]
