# Generated by Django 5.2.6 on 2025-10-10 13:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earnings', '0002_dailyearningsstate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPoolState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_pool_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('last_collection_date', models.DateField(blank=True, null=True)),
                ('last_distribution_date', models.DateField(blank=True, null=True)),
                ('total_collected_all_time', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_distributed_all_time', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Pool State',
                'verbose_name_plural': 'Global Pool State',
            },
        ),
        migrations.CreateModel(
            name='GlobalPoolCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_amount_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('collection_amount_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('collection_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_pool_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'collection_date')},
            },
        ),
        migrations.CreateModel(
            name='GlobalPoolDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('distribution_date', models.DateField()),
                ('total_pool_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_users', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_pool_distributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'distribution_date')},
            },
        ),
    ]
