# Generated by Django 5.0.7 on 2025-08-30 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_pkr', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fx_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('method', models.CharField(choices=[('BANK', 'Bank'), ('EASYPaisa', 'EasyPaisa'), ('JAZZCASH', 'JazzCash')], max_length=20)),
                ('account_details', models.JSONField(default=dict)),
                ('tax_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
