# Generated by Django 5.0.7 on 2025-08-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='tx_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
