# Generated by Django 5.0.7
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0002_withdrawalrequest_tx_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='bank_name',
            field=models.CharField(max_length=120, blank=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='account_name',
            field=models.CharField(max_length=120, blank=True),
        ),
    ]