# Generated by Django 5.0.7
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_depositrequest_proof_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositrequest',
            name='bank_name',
            field=models.CharField(max_length=120, blank=True),
        ),
        migrations.AddField(
            model_name='depositrequest',
            name='account_name',
            field=models.CharField(max_length=120, blank=True),
        ),
    ]