# Generated by Django 5.2.6 on 2025-10-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_depositrequest_bank_and_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='income_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
